name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - develop

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://ravel.andrade:${{ secrets.GITLAB_TOKEN }}@tools.ages.pucrs.br/estudify/frontend-web.git
          git push gitlab --all
          git push gitlab --tags
